name: End to end tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            os: ubuntu-latest,
            cc: clang-12, cxx: clang++-12,
          }
        build_type: [ RelWithDebInfo ]
        stl_implementation: [ libstdc++ ]
        sanitizer: [ ASAN, TSAN, UBSAN, OFF ]
        target: [ lexer, parser ]

    name: "${{ matrix.target }} / ${{ matrix.config.os }} / ${{ matrix.sanitizer }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip
          pip install termcolor

      - name: Configure CMake
        run:
          mkdir build &&
          cd build &&
          cmake ..
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
          -DCMAKE_CXX_FLAGS=-stdlib=${{ matrix.stl_implementation }}
          -DCOOLC_SANITIZER=${{ matrix.sanitizer }}

      - name: Build
        run:
          cmake --build build --config ${{ matrix.build_type }} -j --target ${{ matrix.target }}

      - name: Test
        run:
          test/e2e/test_runner  -t test/e2e/${{ matrix.target }} -e build/main/${{ matrix.target }}
